export const HostelData = [
  {
    id: 1,
    img: "https://cms.hostelworld.com/hwblog/wp-content/uploads/sites/2/2019/01/7-1.jpg",
    Hostelname: "Earlybird Hostel",
    location: "Banglore",
    interest: "Sports",
    currentuser: "John, David, Ram",
    price: "2500",
    rating: "4.5",
  },
  {
    id: 2,
    img: "https://q-xx.bstatic.com/xdata/images/hotel/840x460/232170506.jpg?k=289df3071803a2a7374b34c9fb956b6d8884ecf9c6d17ddf8c597bbc1cbdfaa3&o=",
    Hostelname: "Glamour Hostel",
    location: "Chennai",
    interest: "Art",
    currentuser: "Venkat, Joseph",
    price: "1200",
    rating: "4.2",
  },
  {
    id: 3,
    img: "https://hostelgeeks.com/wp-content/uploads/2016/04/hostel-room-types-dorms-1200x630-cropped.jpg",
    Hostelname: "Hostel Cube",
    location: "Hyderabad",
    interest: "Music",
    currentuser: "Krishna, Suman",
    price: "1800",
    rating: "4.7",
  },
  {
    id: 4,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8Lu4Y1r05jqiT5SMYdrRdGPmnMkfXkfSn1Il3VvFQKses4n-GNe8ImNDOEW3wlWITT8k&usqp=CAU",
    Hostelname: "Kangaroo Hostel",
    location: "Delhi",
    interest: "Photography",
    currentuser: "Manu, Pavan, Sai",
    price: "3400",
    rating: "4.3",
  },
  {
    id: 5,
    img: "https://media-cdn.tripadvisor.com/media/photo-s/12/50/8b/bf/mad-monkey-hostel-boracay.jpg",
    Hostelname: "Allstar Hostel",
    location: "Mumbai",
    interest: "Dance",
    currentuser: "Ganesh, Arjun",
    price: "3800",
    rating: "4.5",
  },
  {
    id: 6,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRJNrzRIiOpH8V0nM-x08cTco3TEOQV4G6KNQ&usqp=CAU",
    Hostelname: "Candle Hostel",
    location: "Kolkata",
    interest: "Travel",
    currentuser: "Avinash, Chaitanya, Abhay",
    price: "2200",
    rating: "4.4",
  },
  {
    id: 7,
    img: "https://www.bowringandladycurzonmedicalcollege.org/wp-content/uploads/2020/11/3a.jpg",
    Hostelname: "Bliss Hostel",
    location: "Jaipur",
    interest: "Fitness",
    currentuser: "Anirudh, Mahesh",
    price: "1900",
    rating: "3.9",
  },
  {
    id: 8,
    img: "https://qph.fs.quoracdn.net/main-qimg-47fff53340e963082827560fa060fcd0",
    Hostelname: "Classic Hostel",
    location: "Lucknow",
    interest: "Music",
    currentuser: "Salman, Nitish",
    price: "2300",
    rating: "4.1",
  },
  {
    id: 9,
    img: "https://5.imimg.com/data5/WX/JV/GLADMIN-31139027/ac-room-service-500x500.png",
    Hostelname: "Dolphin Hostel",
    location: "Visakhapatnam",
    interest: "Photography",
    currentuser: "Kumar, Kiran, Manohar",
    price: "2800",
    rating: "4.6",
  },
  {
    id: 10,
    img: "https://i.pinimg.com/236x/ce/a9/4b/cea94bb9ce132303dfddea920452656d.jpg",
    Hostelname: "Nomadic Hostel",
    location: "Srinagar",
    interest: "Travel",
    currentuser: "Ali, Jimmy",
    price: "3100",
    rating: "4.1",
  },
  {
    id: 11,
    img: "https://is1-2.housingcdn.com/01c16c28/7a1ecb927def237d68c71fb2ea6a1eae/v0/fs/3_rk_-for-rent-narayan_peth-Pune-triple_sharing_room.jpg",
    Hostelname: "Pacific Hostel",
    location: "Banglore",
    interest: "Dance",
    currentuser: "Ishaq, Raghu",
    price: "3200",
    rating: "4.2",
  },
  {
    id: 12,
    img: "https://www.bitm.edu.in/wp-content/uploads/2020/08/gh8.jpg",
    Hostelname: "Penguin Hostel",
    location: "Chennai",
    interest: "Fitenss",
    currentuser: "Anand, Imran, Jones",
    price: "2900",
    rating: "3.6",
  },
  {
    id: 13,
    img: "https://iimamritsar.ac.in/uploads/userfiles/images/hostel10.jpg",
    Hostelname: "Natural Hostel",
    location: "Hyderabad",
    interest: "Sports",
    currentuser: "Aravind, Jaswanth, Shakib",
    price: "4500",
    rating: "4.8",
  },
  {
    id: 14,
    img: "https://sgtuniversity.ac.in/wp-content/uploads/2021/02/h-1.jpg",
    Hostelname: "Noble Hostel",
    location: "Delhi",
    interest: "Art",
    currentuser: "Vamsi, Don",
    price: "1800",
    rating: "3.2",
  },
  {
    id: 15,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR5No_IigaMOjW8AcU6aTy12_-SLftU106Nfg&usqp=CAU",
    Hostelname: "Mirror Hostel",
    location: "Mumbai",
    interest: "Music",
    currentuser: "Madhav, Gopal, Nandu",
    price: "2900",
    rating: "3.7",
  },
  {
    id: 16,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSyPqibdgWTpw3OKpTbrTHpyUf02B7vhp_eEQ&usqp=CAU",
    Hostelname: "Knight Hostel",
    location: "Kolkata",
    interest: "Photography",
    currentuser: "Dattu, Karan, Satish",
    price: "5100",
    rating: "4.8",
  },
  {
    id: 17,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTD4sbBorglXcp3BI0zRzRf0327Zcr9mMM3yg&usqp=CAU",
    Hostelname: "Kings Hostel",
    location: "Jaipur",
    interest: "Travel",
    currentuser: "Avinash, Rahul, Amith",
    price: "4000",
    rating: "4.0",
  },
  {
    id: 18,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRbhNP6QiZRkaOCdCyJs8WHPSdskyYeODRCbg&usqp=CAU",
    Hostelname: "Kiwi Hostel",
    location: "Lucknow",
    interest: "Dance",
    currentuser: "Venu, Srinu, Jagan",
    price: "3300",
    rating: "4.1",
  },
  {
    id: 19,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcStSrBgTU_8szNWsXrj7bDAuzyyBdbowDnFWA&usqp=CAU",
    Hostelname: "Honeybee Hostel",
    location: "Visakhapatnam",
    interest: "Fitness",
    currentuser: "Bobby, Arjun",
    price: "3600",
    rating: "4.5",
  },
  {
    id: 20,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQgwBG6pBQDZopA3l63H7nUOmTbj4Lx57GLZA&usqp=CAU",
    Hostelname: "Grizzly Hostel",
    location: "Srinagar",
    interest: "Art",
    currentuser: "Kamal, Rajesh, Shahib",
    price: "4200",
    rating: "4.4",
  },
  {
    id: 21,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_AJXLJYmPOayEnPA-HMCGMZwR4ebhI176R2Pzu2fbdOo76ORXZeHn_jiDuwj2ervXoKo&usqp=CAU",
    Hostelname: "Greenlife Hostel",
    location: "Banglore",
    interest: "Sports",
    currentuser: "Jayesh, Sai, Murali",
    price: "5000",
    rating: "4.7",
  },
  {
    id: 22,
    img: "https://us.123rf.com/450wm/razvanphoto/razvanphoto1603/razvanphoto160300041/53401973-clean-hostel-room-with-bed-and-wardrobe.jpg?ver=6",
    Hostelname: "Graphic Hostel",
    location: "Chennai",
    interest: "Music",
    currentuser: "Akash, Jai",
    price: "2900",
    rating: "4.6",
  },
  {
    id: 23,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRRWogAPU3P0UGB4GyDaPaQcs9uGr8GWDh_eVwl9y_b24hY88GqZl-6DlwSa_sWXz_neZw&usqp=CAU",
    Hostelname: "Goldfish Hostel",
    location: "Hyderabad",
    interest: "Travel",
    currentuser: "Anudeep, Raj, Siva",
    price: "4800",
    rating: "4.3",
  },
  {
    id: 24,
    img: "https://images.jdmagicbox.com/comp/nellore/r9/9999px861.x861.181119163414.t5r9/catalogue/dbr-boys-hostel-nellore-ho-nellore-hostels-ws2rgjc8lq.jpg",
    Hostelname: "Firebird Hostel",
    location: "Delhi",
    interest: "Photography",
    currentuser: "Ravi, Albert, Chris",
    price: "3500",
    rating: "4.2",
  },
  {
    id: 25,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQkmQCtSXz1hghEKZ6x77BobssJQf7DlOqgMA&usqp=CAU",
    Hostelname: "Extreme Hostel",
    location: "Mumbai",
    interest: "Dance",
    currentuser: "Vinay, Sandeep",
    price: "4000",
    rating: "4.0",
  },
  {
    id: 26,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQQwR3OdvStaqfO-aYp3rdRwtaKDy9MY8MtNA&usqp=CAU",
    Hostelname: "Dreamteam Hostel",
    location: "Kolkata",
    interest: "Fitness",
    currentuser: "Bharath, Abdul",
    price: "3500",
    rating: "3.8",
  },
  {
    id: 27,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT2dvrHdWPIf0Quyr310lfhp6Ak5C343KHhaQ&usqp=CAU",
    Hostelname: "Destiny Hostel",
    location: "Jaipur",
    interest: "Art",
    currentuser: "Srikar, Harsha, Akbar",
    price: "3000",
    rating: "4.7",
  },
  {
    id: 28,
    img: "https://is1-2.housingcdn.com/01c16c28/d4aa5ffa3c28e7f638ce410d187a6f50/v0/large/3_rk_-for-rent-karol_bagh-New+Delhi-bedroom.jpg",
    Hostelname: "Crystal Hostel",
    location: "Lucknow",
    interest: "Sports",
    currentuser: "Samuel, Syfar",
    price: "4100",
    rating: "4.5",
  },
  {
    id: 29,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ4udjSWk4OQWG8yD9DrK2ml99Zqc6eqZ_CSw&usqp=CAU",
    Hostelname: "Ceaser Hostel",
    location: "Visakhapatnam",
    interest: "Music",
    currentuser: "Jashwanth, Kiran, Kane",
    price: "3100",
    rating: "4.4",
  },
  {
    id: 30,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQUpWpq09OzZfPCrYt6hmNPJxwvqR7Eo8Pd6A&usqp=CAU",
    Hostelname: "Bluestar Hostel",
    location: "Srinagar",
    interest: "Dance",
    currentuser: "Prasanth, Varma, Charlie",
    price: "2800",
    rating: "4.6",
  },
];
